config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "purchases#index"
  resources :purchases, except: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :purchases

    validates_presence_of :name
end

app/models/merchant.rb
class Merchant < ApplicationRecord
    has_many :products

    validates_presence_of :name, :address
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :merchant
    has_many :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord    
    belongs_to :customer
    belongs_to :product

    def self.create_from_file file
        txt_file_rows = FileParser.call file

        txt_file_rows.each do |row|
            @instance = self.new
            @purchaser_name, @item_description, @item_price,
            @purchase_count, @merchant_address, @merchant_name = row.split "\t", 6

            self.setup_relations
            @instance.save!
        end
    end

    private

    def self.setup_relations
        customer = Customer.find_or_create_by(name: @purchaser_name)
        merchant = Merchant.find_or_create_by(name: @merchant_name, address: @merchant_address)
        product = Product.find_or_create_by(
            description: @item_description,
            price: @item_price,
            merchant: merchant)

        @instance.product_quantity = @purchase_count
        @instance.product = product
        @instance.customer = customer
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[ show destroy ]

  def index
    @purchases = Purchase.all
  end

  def new
    @purchase = Purchase.new
  end

  def create
    if Purchase.create_from_file params[:txt_file]
      redirect_to purchases_url, notice: "Purchase was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @purchase.destroy
    redirect_to purchases_url, notice: "Purchase was successfully destroyed."
  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_with url: '/purchases', multipart: true do |form| %>

  <%= label_tag :txt_file, "Arquivo tab" %>
  <%= file_field_tag :txt_file %>

  <br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<%= link_to 'New Purchase', new_purchase_path %>

<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th> Customer name </th>
      <th> Product Description </th>
      <th> Quantity </th>
      <th> Price </th>
      <th> Merchant Name </th>
      <th> Merchant Address </th>
      <th colspan="2"> Actions </th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>

      <tr>
        <td><%= purchase.id %></td>
        <td><%= purchase.customer.name if purchase.customer %></td>
        <td><%= purchase.product.description if purchase.product %></td>
        <td><%= purchase.product_quantity%></td>
        <td><%= "$  #{purchase.product.price}" if purchase.product %></td>
        <td><%= purchase.product.merchant.name  if purchase.product %></td>
        <td><%= purchase.product.merchant.address if purchase.product %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', purchases_path %>